Họ và tên: Nguyễn Đình Khanh

MSSV: 24110244

Link Github: https://github.com/qilskcter/TriTueNhanTao

## BÀI TẬP VỀ NHÀ

# Máy hút bụi hoạt động khi có nội thất

In [1]:
import random
import numpy as np

ACTION_SUCK = "SUCK"
MOVE_UP = "UP"
MOVE_DOWN = "DOWN"
MOVE_LEFT = "LEFT"
MOVE_RIGHT = "RIGHT"

DIRTY = "DIRTY"
CLEAN = "CLEAN"
OBSTACLE = "OBSTACLE"

DIRTY_VAL = 1
CLEAN_VAL = 0
OBSTACLE_VAL = -1

In [2]:
def interpret_input_with_furniture(matrix, location):
    x, y = location
    val = matrix[x, y]
    
    if val == DIRTY_VAL:
        status = DIRTY
    elif val == OBSTACLE_VAL:
        status = OBSTACLE
    else:
        status = CLEAN
        
    return {'location': location, 'status': status}

In [3]:
def rule_match_with_furniture(state, max_x, max_y, matrix):
    if state['status'] == DIRTY:
        return ACTION_SUCK
    
    x, y = state['location']
    possible_moves = []
    
    if x > 0 and matrix[x-1, y] != OBSTACLE_VAL:
        possible_moves.append(MOVE_UP)
    if x < max_x and matrix[x+1, y] != OBSTACLE_VAL:
        possible_moves.append(MOVE_DOWN)
    if y > 0 and matrix[x, y-1] != OBSTACLE_VAL:
        possible_moves.append(MOVE_LEFT)
    if y < max_y and matrix[x, y+1] != OBSTACLE_VAL:
        possible_moves.append(MOVE_RIGHT)
    
    if not possible_moves:
        return None
        
    return random.choice(possible_moves)

def simple_reflex_agent_furnished(percept, max_x, max_y):
    state = interpret_input_with_furniture(percept['matrix'], percept['location'])
    return rule_match_with_furniture(state, max_x, max_y, percept['matrix'])

In [4]:
def create_furnished_floor(rows, cols, dirty_prob=0.3, furniture_prob=0.2):
    # 0: Sạch, 1: Bẩn, -1: Nội thất
    choices = [CLEAN_VAL, DIRTY_VAL, OBSTACLE_VAL]
    probs = [1 - dirty_prob - furniture_prob, dirty_prob, furniture_prob]
    
    floor = np.random.choice(choices, size=(rows, cols), p=probs)
    
    # Đảm bảo điểm bắt đầu (0,0) không phải là nội thất
    if floor[0, 0] == OBSTACLE_VAL:
        floor[0, 0] = CLEAN_VAL
        
    return floor

In [5]:
rows, cols = 5, 5
floor_matrix = create_furnished_floor(rows, cols)
current_pos = [0, 0]
max_steps = 100
step_count = 0

print("Ma trận sàn nhà (1: Bẩn, 0: Sạch, -1: Nội thất):")
print(floor_matrix)

while np.any(floor_matrix == DIRTY_VAL) and step_count < max_steps:
    percept = {
        'matrix': floor_matrix.copy(), # Gửi bản sao để tránh can thiệp trực tiếp
        'location': tuple(current_pos)
    }
    
    action = simple_reflex_agent_furnished(percept, rows-1, cols-1)
    
    if action is None:
        print(f"Bước {step_count + 1}: Robot bị kẹt tại {current_pos} do nội thất!")
        break
        
    print(f"Bước {step_count + 1}: Tại {current_pos} -> Quyết định: {action}")
    
    if action == ACTION_SUCK:
        floor_matrix[current_pos[0], current_pos[1]] = CLEAN_VAL
    elif action == MOVE_UP: current_pos[0] -= 1
    elif action == MOVE_DOWN: current_pos[0] += 1
    elif action == MOVE_LEFT: current_pos[1] -= 1
    elif action == MOVE_RIGHT: current_pos[1] += 1
    
    step_count += 1

print("\n--- KẾT QUẢ ---")
print(floor_matrix)
if not np.any(floor_matrix == DIRTY_VAL):
    print(f"Thành công! Sàn sạch sau {step_count} bước.")
else:
    print(f"Dừng lại sau {step_count} bước.")

Ma trận sàn nhà (1: Bẩn, 0: Sạch, -1: Nội thất):
[[ 0  1  0  0  1]
 [ 0  0  0  1  0]
 [ 1  1 -1  0 -1]
 [ 1  0  0  1  0]
 [-1  0  0  0  1]]
Bước 1: Tại [0, 0] -> Quyết định: RIGHT
Bước 2: Tại [0, 1] -> Quyết định: SUCK
Bước 3: Tại [0, 1] -> Quyết định: RIGHT
Bước 4: Tại [0, 2] -> Quyết định: DOWN
Bước 5: Tại [1, 2] -> Quyết định: RIGHT
Bước 6: Tại [1, 3] -> Quyết định: SUCK
Bước 7: Tại [1, 3] -> Quyết định: LEFT
Bước 8: Tại [1, 2] -> Quyết định: UP
Bước 9: Tại [0, 2] -> Quyết định: DOWN
Bước 10: Tại [1, 2] -> Quyết định: LEFT
Bước 11: Tại [1, 1] -> Quyết định: LEFT
Bước 12: Tại [1, 0] -> Quyết định: RIGHT
Bước 13: Tại [1, 1] -> Quyết định: DOWN
Bước 14: Tại [2, 1] -> Quyết định: SUCK
Bước 15: Tại [2, 1] -> Quyết định: LEFT
Bước 16: Tại [2, 0] -> Quyết định: SUCK
Bước 17: Tại [2, 0] -> Quyết định: DOWN
Bước 18: Tại [3, 0] -> Quyết định: SUCK
Bước 19: Tại [3, 0] -> Quyết định: RIGHT
Bước 20: Tại [3, 1] -> Quyết định: DOWN
Bước 21: Tại [4, 1] -> Quyết định: UP
Bước 22: Tại [3, 1] -> Quyết